### ISSUE TITLE
Outside Connection To Server

### ISSUE THREAD

**Issue by MrMoonCrypto** [kirill190497/BoomTrader#1]
https://github.com/kirill190497/BoomTrader/blob/338278e7260c372cad82f4248b6ee3f2d2a882c8/BoomTrader_2/Settings/Security.cs#L99

What is this line for? Why is the bot contacting a outside server and sending a string of info?
What is the purpose of this feature?

**Comment by kirill190497** [comment]
Now this server is not used, it remains from the license check
`Security.checkLicence (string key, string wallet) method is not used in this version`
