### ISSUE TITLE
Running it doesn't work.

### ISSUE THREAD

**Issue by pubill** [kirill190497/BoomTrader#3]
I think your program is amazing. and Thanks. 

But it doesn't work when run. 

Do you have the required installation package to run the program? 

Please tell me what components you need to run this program. 

I hope you read this post.

**Comment by kirill190497** [comment]
.Net core runtime 3.1 must be installed to run

**Comment by pubill** [comment]
I installed .Net Core runtime 3.1.  
But it doesn't work.  
Are there any other dependency programs?

**Comment by pubill** [comment]
I think there is a problem with this part. 

MainForm.cs :260
                var settings = Request.GetJSON("https://license.boomtrader.info/settings/default", "");

It looks like the part where you get the setting ini file, but your domain is not alive, so I can't get it. 

How can I fix this?

**Comment by kirill190497** [comment]
Oh yes I forgot about that, remove or comment out this line and compile

**Comment by kirill190497** [comment]
well and fix a few errors that appear after that

**Comment by kirill190497** [comment]
write me in telegram if I can tell you what and how
